name: Testar_Noturno

on:
  schedule:
    - cron: '0 23 * * * '
  push:
    branchs:
      - main
jobs:
  teste_noturno:
    runs-on: self-hosted
    steps: 
      - name: "Iniciando JOB"
        run: |
          echo "Iniciando JOB em $(date)"
      - name: "Checkout codigo"
        uses: actions/checkout@v4
      - name: "Configurar Ambiente"
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: "Instalar Dependencias"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  